//! Fuzz `dafs_enrich::parse_chat_response`.
//!
//! # Why this target exists
//!
//! `docs/m03-semantic-search.md`'s "Deliberately not done" section flagged
//! this as an existing M02b gap that also applies to `embed`'s parser (see
//! `embed_response.rs`): `dafs_enrich::enrich` parses a chat-completions
//! response body — network-supplied JSON from whatever endpoint
//! `--llm-base-url` names — the same class of untrusted input every other
//! fuzz target in this crate exercises, just arriving over HTTP instead of
//! from a file on disk.
//!
//! # Why through `parse_chat_response`, not a mock HTTP server
//!
//! `dafs_enrich::enrich` itself makes a real blocking network call before it
//! ever reaches parsing, which a fuzz target has no use for — libFuzzer wants
//! a pure `bytes -> outcome` function, not one that opens a socket. M03's
//! embeddings work (`docs/m03-semantic-search.md`) split the network call and
//! the parsing into `embed`/`parse_embedding_response` for exactly this
//! reason (a fuzz target was always the point); `enrich`'s own parsing got
//! the same treatment as `parse_chat_response`, a `pub` function taking the
//! response body directly.
//!
//! # The property asserted
//!
//! No panic, no hang. Every failure mode `parse_chat_response` has is a
//! typed `EnrichError` returned to the caller — a malformed envelope, no
//! choices, no JSON in the reply, an unexpected reply shape are all `Err`,
//! the ordinary outcome for fuzzed input, not a bug. Only a panic or an
//! infinite loop is one.
#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    // Lossy rather than skipping invalid UTF-8: `parse_chat_response` takes
    // `&str`, and converting lossily means every fuzzer-generated byte
    // string still drives a real call (exercising the replacement-character
    // path too) instead of a no-op run whenever the random bytes are not
    // valid UTF-8, which would be most of them.
    let body = String::from_utf8_lossy(data);
    let _ = dafs_enrich::parse_chat_response(&body);
});
